exclude: [config.rb, nginx.conf, Makefile, README.md, .gitignore, .gitmodules, server]
include: ['pages']
# destination: /home/lucas/www/
# source: /home/
markdown: rdiscount
highlighter: pygments
permalink: /:title
rdiscount:
  extensions: [smart]
