exclude: [config.rb, nginx.conf, Makefile, README.md, build.sh, .gitignore, .gitmodules, server]
include: ['pages']
# destination: /home/lucas/www/
# source: /home/
markdown: rdiscount
pygments: true
permalink: /:title
rdiscount:
  extensions: [smart]
