exclude: [config.rb, nginx.conf, Makefile, README.md, build.sh, .gitignore, .gitmodules]
destination: /home/louyang/webapps/codelucas/
markdown: rdiscount
pygments: true
permalink: /:title
rdiscount:
  extensions: [smart]
